DockerfileGen 需求说明文档
. 项目概述
项目名称：DockerfileGen
项目定位：一款针对 Docker Hub 镜像的自动化逆向工程工具。
核心价值：解决 Docker 镜像在分发过程中丢失原始构建文件（Dockerfile）的问题。通过扫描和分析 Docker Hub 上的镜像层（Layers）及元数据，自动生成高度还原的 Dockerfile，帮助开发者理解镜像构成、进行安全审计及二次开发。
. 用户故事与痛点
痛点：开发者在 Docker Hub 上拉取镜像时，往往只能看到最终产物，无法得知具体的构建步骤、基础镜像版本或环境配置，导致维护和排障困难。
用户故事：作为一名 DevOps 工程师，我希望输入一个 Docker Hub 镜像名称（如 nginx:latest），工具能自动分析并输出一个可运行的 Dockerfile，以便我了解其构建逻辑并进行定制化修改。
. 功能需求
.1 核心功能
镜像拉取与解析：
支持通过 Docker Hub API 或本地 Docker Daemon 获取指定镜像。
能够解析镜像的 Manifest 和 Config 文件，提取基础镜像信息、环境变量、暴露端口等元数据。
层级扫描与分析：
遍历镜像的所有 Layer（层），分析每一层的指令历史（History）。
识别 created_by 字段中的构建指令（如 RUN, COPY, ADD, WORKDIR 等）。
Dockerfile 自动生成：
将解析出的指令逆向还原为标准的 Dockerfile 语法。
自动推导 FROM 指令（基于基础镜像的 SHA256 或标签）。
合并连续的 RUN 指令（可选，保持生成文件的整洁）。
导出与保存：
支持将生成的 Dockerfile 内容直接打印到终端（Stdout）。
支持通过 -o 参数将结果保存为本地 Dockerfile 文件。
.2 辅助功能
差异对比：如果本地存在 Dockerfile，可对比生成的 Dockerfile 与原始文件的差异。
多标签支持：支持一次性扫描同一个镜像仓库下的多个标签（Tag）。
. 非功能需求
准确性：生成的 Dockerfile 必须语法正确，且尽可能还原原始构建意图（例如正确还原被转义的字符）。
性能：对于大型镜像（如 1GB+），扫描和生成过程应在合理时间内完成（建议 < 30秒）。
兼容性：生成的 Dockerfile 应兼容主流 Docker 引擎（Docker CE/EE, Podman）。
易用性：提供简洁的命令行界面（CLI），参数简单易懂。
. 技术栈建议
开发语言：Go (Golang) —— 因其出色的并发处理能力和在云原生领域的广泛生态（类似 Docker, K8s 的编写语言）。
核心库：
google/go-containerregistry：用于与 Docker Registry 交互，拉取镜像配置和层。
moby/buildkit：用于解析 Dockerfile 语法和构建逻辑。
打包方式：提供静态编译的二进制文件，同时提供 Docker 镜像版本的工具本身。
. 输入输出示例
输入命令：

dockerfilegen scan -i nginx:1.21-alpine -o ./restored_Dockerfile
输出文件内容（预期效果）：

# Generated by DockerfileGen
FROM nginx:1.21-alpine@sha256:abc123...

# Metadata
ENV NGINX_VERSION 1.21.0
EXPOSE 80

# Commands
RUN addgroup -S nginx && adduser -S -G nginx nginx
RUN mkdir -p /var/cache/nginx
COPY file:abc123 in /etc/nginx/nginx.conf 
# ...
. 阶段性规划
第一阶段（MVP）：实现本地镜像的扫描与基础 Dockerfile 生成（还原 FROM, ENV, RUN, CMD）。
第二阶段：接入 Docker Hub API，支持直接扫描远程镜像，优化 COPY/ADD 指令的文件路径还原。
第三阶段：增加多语言支持、JSON 格式输出以及 CI/CD 集成插件。
这份需求文档涵盖了从核心功能到技术选型的完整规划，你觉得目前的规划符合你的预期吗？
