package generator

import (
	"strings"
	"testing"

	"github.com/TDnorthgarden/DockerfileGen/internal/model"
)

func TestRenderBasic(t *testing.T) {
	meta := model.ImageMetadata{
		BaseImageRef: "nginx:1.21-alpine@sha256:abc123",
		EnvVars:      map[string]string{"NGINX_VERSION": "1.21.0"},
		ExposedPorts: []string{"80/tcp"},
	}

	instructions := []model.Instruction{
		{Type: model.InstRUN, Content: "apk add --no-cache curl"},
		{Type: model.InstWORKDIR, Content: "/app"},
	}

	result := Render(meta, instructions, false)

	if !strings.Contains(result, "FROM nginx:1.21-alpine@sha256:abc123") {
		t.Error("missing FROM instruction")
	}
	if !strings.Contains(result, "RUN apk add --no-cache curl") {
		t.Error("missing RUN instruction")
	}
	if !strings.Contains(result, "WORKDIR /app") {
		t.Error("missing WORKDIR instruction")
	}
	if !strings.Contains(result, "# Generated by DockerfileGen") {
		t.Error("missing header comment")
	}
}

func TestRenderDeduplicatesMetadata(t *testing.T) {
	meta := model.ImageMetadata{
		BaseImageRef: "alpine:3.18",
		EnvVars:      map[string]string{"PATH": "/usr/bin"},
	}

	// History already has ENV — metadata ENV should not duplicate
	instructions := []model.Instruction{
		{Type: model.InstENV, KVPairs: map[string]string{"PATH": "/usr/bin"}},
	}

	result := Render(meta, instructions, false)

	count := strings.Count(result, "ENV ")
	if count != 1 {
		t.Errorf("ENV appears %d times, want 1 (dedup failed)", count)
	}
}

func TestRenderCMDJson(t *testing.T) {
	meta := model.ImageMetadata{
		BaseImageRef: "nginx:latest",
		Cmd:          []string{"nginx", "-g", "daemon off;"},
	}

	result := Render(meta, nil, false)

	if !strings.Contains(result, `CMD ["nginx", "-g", "daemon off;"]`) {
		t.Errorf("CMD not rendered correctly:\n%s", result)
	}
}

func TestRenderENTRYPOINT(t *testing.T) {
	meta := model.ImageMetadata{
		BaseImageRef: "nginx:latest",
		Entrypoint:   []string{"/docker-entrypoint.sh"},
	}

	result := Render(meta, nil, false)

	if !strings.Contains(result, `ENTRYPOINT ["/docker-entrypoint.sh"]`) {
		t.Errorf("ENTRYPOINT not rendered correctly:\n%s", result)
	}
}

func TestMergeRuns(t *testing.T) {
	instructions := []model.Instruction{
		{Type: model.InstRUN, Content: "apt-get update"},
		{Type: model.InstRUN, Content: "apt-get install -y curl"},
		{Type: model.InstRUN, Content: "rm -rf /var/lib/apt/lists/*"},
		{Type: model.InstWORKDIR, Content: "/app"},
	}

	merged := MergeRuns(instructions)
	if len(merged) != 2 {
		t.Fatalf("expected 2 instructions after merge, got %d", len(merged))
	}
	if merged[0].Type != model.InstRUN {
		t.Errorf("merged[0] type = %q, want RUN", merged[0].Type)
	}
	if !strings.Contains(merged[0].Content, "apt-get update") {
		t.Error("merged RUN missing first command")
	}
	if !strings.Contains(merged[0].Content, "apt-get install -y curl") {
		t.Error("merged RUN missing second command")
	}
	if merged[1].Type != model.InstWORKDIR {
		t.Errorf("merged[1] type = %q, want WORKDIR", merged[1].Type)
	}
}

func TestMergeRunsNoConsecutive(t *testing.T) {
	instructions := []model.Instruction{
		{Type: model.InstRUN, Content: "apt-get update"},
		{Type: model.InstWORKDIR, Content: "/app"},
		{Type: model.InstRUN, Content: "apt-get install -y curl"},
	}

	merged := MergeRuns(instructions)
	if len(merged) != 3 {
		t.Fatalf("expected 3 instructions (no merge), got %d", len(merged))
	}
}

func TestRenderENVQuoting(t *testing.T) {
	meta := model.ImageMetadata{
		BaseImageRef: "test:latest",
		EnvVars:      map[string]string{"MSG": "hello world"},
	}

	result := Render(meta, nil, false)

	if !strings.Contains(result, `ENV MSG="hello world"`) {
		t.Errorf("ENV value with spaces should be quoted:\n%s", result)
	}
}
