package generator

import (
	"fmt"
	"sort"
	"strings"

	"github.com/TDnorthgarden/DockerfileGen/internal/model"
)

const maxLineLen = 80

// Render assembles metadata and history instructions into a Dockerfile string.
func Render(meta model.ImageMetadata, instructions []model.Instruction, mergeRuns bool) string {
	var b strings.Builder

	b.WriteString("# Generated by DockerfileGen\n")
	b.WriteString(fmt.Sprintf("FROM %s\n", meta.BaseImageRef))

	// Track which types already appear in history for metadata fallback
	historyTypes := make(map[model.InstructionType]bool)
	for _, inst := range instructions {
		historyTypes[inst.Type] = true
	}

	// Metadata directives (from image config) — placed after FROM, before history
	hasMeta := false

	if !historyTypes[model.InstENV] && len(meta.EnvVars) > 0 {
		keys := sortedKeys(meta.EnvVars)
		b.WriteString("\n")
		hasMeta = true
		for _, k := range keys {
			b.WriteString(fmt.Sprintf("ENV %s=%s\n", k, quoteVal(meta.EnvVars[k])))
		}
	}

	if !historyTypes[model.InstLABEL] && len(meta.Labels) > 0 {
		keys := sortedKeys(meta.Labels)
		if !hasMeta {
			b.WriteString("\n")
		}
		hasMeta = true
		for _, k := range keys {
			b.WriteString(fmt.Sprintf("LABEL %s=%s\n", k, quoteVal(meta.Labels[k])))
		}
	}

	if !historyTypes[model.InstEXPOSE] && len(meta.ExposedPorts) > 0 {
		if !hasMeta {
			b.WriteString("\n")
		}
		hasMeta = true
		for _, port := range meta.ExposedPorts {
			b.WriteString(fmt.Sprintf("EXPOSE %s\n", port))
		}
	}

	if !historyTypes[model.InstWORKDIR] && meta.WorkingDir != "" {
		if !hasMeta {
			b.WriteString("\n")
		}
		hasMeta = true
		b.WriteString(fmt.Sprintf("WORKDIR %s\n", meta.WorkingDir))
	}

	if !historyTypes[model.InstUSER] && meta.User != "" {
		if !hasMeta {
			b.WriteString("\n")
		}
		hasMeta = true
		b.WriteString(fmt.Sprintf("USER %s\n", meta.User))
	}

	if !historyTypes[model.InstVOLUME] && len(meta.Volumes) > 0 {
		if !hasMeta {
			b.WriteString("\n")
		}
		for _, vol := range meta.Volumes {
			b.WriteString(fmt.Sprintf("VOLUME %q\n", vol))
		}
	}

	// History-derived instructions
	if len(instructions) > 0 {
		if mergeRuns {
			instructions = MergeRuns(instructions)
		}
		b.WriteString("\n")
		for _, inst := range instructions {
			rendered := renderInstruction(inst)
			if rendered != "" {
				b.WriteString(rendered)
				b.WriteString("\n")
			}
		}
	}

	// ENTRYPOINT / CMD from metadata (if not in history) — placed at the end
	if !historyTypes[model.InstENTRYPOINT] && len(meta.Entrypoint) > 0 {
		b.WriteString(fmt.Sprintf("\nENTRYPOINT %s\n", formatJSONCmd(meta.Entrypoint)))
	}

	if !historyTypes[model.InstCMD] && len(meta.Cmd) > 0 {
		b.WriteString(fmt.Sprintf("\nCMD %s\n", formatJSONCmd(meta.Cmd)))
	}

	return b.String()
}

// renderInstruction converts a single Instruction to its Dockerfile text.
func renderInstruction(inst model.Instruction) string {
	switch inst.Type {
	case model.InstRUN:
		return renderRUN(inst.Content)
	case model.InstCOPY:
		return fmt.Sprintf("COPY %s", inst.Content)
	case model.InstADD:
		return fmt.Sprintf("ADD %s", inst.Content)
	case model.InstWORKDIR:
		return fmt.Sprintf("WORKDIR %s", inst.Content)
	case model.InstENV:
		return renderKV("ENV", inst.KVPairs)
	case model.InstEXPOSE:
		return fmt.Sprintf("EXPOSE %s", inst.Content)
	case model.InstCMD:
		return renderCmdEntry("CMD", inst)
	case model.InstENTRYPOINT:
		return renderCmdEntry("ENTRYPOINT", inst)
	case model.InstLABEL:
		return renderKV("LABEL", inst.KVPairs)
	case model.InstUSER:
		return fmt.Sprintf("USER %s", inst.Content)
	case model.InstSTOPSIGNAL:
		return fmt.Sprintf("STOPSIGNAL %s", inst.Content)
	case model.InstARG:
		return fmt.Sprintf("ARG %s", inst.Content)
	case model.InstVOLUME:
		return renderCmdEntry("VOLUME", inst)
	case model.InstSHELL:
		return renderCmdEntry("SHELL", inst)
	case model.InstHEALTHCHECK:
		return fmt.Sprintf("HEALTHCHECK %s", inst.Content)
	case model.InstCOMMENT:
		return inst.Content
	default:
		return ""
	}
}

// renderRUN formats a RUN instruction, stripping /bin/sh -c and wrapping long lines.
func renderRUN(content string) string {
	// Strip "/bin/sh -c " prefix — RUN already implies shell execution
	content = strings.TrimPrefix(content, "/bin/sh -c ")

	if len(content) <= maxLineLen {
		return fmt.Sprintf("RUN %s", content)
	}

	// Split on "&&" and render with backslash continuation
	parts := splitOnLogical(content)
	if len(parts) <= 1 {
		return wrapLongLine("RUN ", content)
	}

	var b strings.Builder
	b.WriteString("RUN ")
	for i, part := range parts {
		part = strings.TrimSpace(part)
		if i == 0 {
			b.WriteString(part)
		} else {
			b.WriteString(" && \\\n    ")
			b.WriteString(part)
		}
	}
	return b.String()
}

// splitOnLogical splits a shell command on top-level "&&" and ";" boundaries.
func splitOnLogical(s string) []string {
	var parts []string
	var current strings.Builder
	depth := 0
	runes := []rune(s)
	i := 0

	for i < len(runes) {
		ch := runes[i]

		switch ch {
		case '(', '{', '[':
			depth++
			current.WriteRune(ch)
		case ')', '}', ']':
			if depth > 0 {
				depth--
			}
			current.WriteRune(ch)
		case '"', '\'':
			// skip quoted strings
			current.WriteRune(ch)
			quote := ch
			i++
			for i < len(runes) && runes[i] != quote {
				current.WriteRune(runes[i])
				if runes[i] == '\\' && i+1 < len(runes) {
					i++
					current.WriteRune(runes[i])
				}
				i++
			}
			if i < len(runes) {
				current.WriteRune(runes[i])
			}
		default:
			if depth == 0 && ch == '&' && i+1 < len(runes) && runes[i+1] == '&' {
				parts = append(parts, current.String())
				current.Reset()
				i++ // skip second &
			} else {
				current.WriteRune(ch)
			}
		}
		i++
	}

	if current.Len() > 0 {
		parts = append(parts, current.String())
	}

	return parts
}

// wrapLongLine splits a long instruction at maxLineLen using backslash continuation.
func wrapLongLine(prefix, content string) string {
	var b strings.Builder
	b.WriteString(prefix)

	remaining := content
	first := true
	for len(remaining) > 0 {
		if !first {
			b.WriteString("\\\n    ")
		}
		first = false

		if len(remaining) <= maxLineLen-b.Len() {
			b.WriteString(remaining)
			break
		}

		// Find a good break point (space) within the line limit
		cut := maxLineLen - b.Len()
		if cut <= 0 {
			cut = maxLineLen
		}
		spaceIdx := strings.LastIndex(remaining[:cut], " ")
		if spaceIdx <= 0 {
			spaceIdx = cut
		}
		b.WriteString(remaining[:spaceIdx])
		remaining = strings.TrimLeft(remaining[spaceIdx:], " ")
	}

	return b.String()
}

// renderKV formats ENV or LABEL instructions with key=value pairs.
func renderKV(keyword string, kvps map[string]string) string {
	if len(kvps) == 0 {
		return ""
	}
	keys := sortedKeys(kvps)
	var parts []string
	for _, k := range keys {
		parts = append(parts, fmt.Sprintf("%s=%s", k, quoteVal(kvps[k])))
	}
	return fmt.Sprintf("%s %s", keyword, strings.Join(parts, " "))
}

// renderCmdEntry formats CMD, ENTRYPOINT, SHELL, VOLUME.
func renderCmdEntry(keyword string, inst model.Instruction) string {
	if len(inst.Args) > 0 {
		return fmt.Sprintf("%s %s", keyword, formatJSONCmd(inst.Args))
	}
	if inst.Content != "" {
		return fmt.Sprintf("%s %s", keyword, inst.Content)
	}
	return ""
}

func formatJSONCmd(args []string) string {
	quoted := make([]string, len(args))
	for i, a := range args {
		quoted[i] = fmt.Sprintf("%q", a)
	}
	return fmt.Sprintf("[%s]", strings.Join(quoted, ", "))
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func quoteVal(v string) string {
	if strings.ContainsAny(v, " \t\n\"") {
		return fmt.Sprintf("%q", v)
	}
	return v
}
