package generator

import (
	"fmt"
	"sort"
	"strings"

	"github.com/TDnorthgarden/DockerfileGen/internal/model"
)

// Render assembles metadata and history instructions into a Dockerfile string.
func Render(meta model.ImageMetadata, instructions []model.Instruction, mergeRuns bool) string {
	var b strings.Builder

	b.WriteString("# Generated by DockerfileGen\n")
	b.WriteString(fmt.Sprintf("FROM %s\n", meta.BaseImageRef))

	// Collect instruction types already present in history to avoid duplication
	historyTypes := make(map[model.InstructionType]bool)
	for _, inst := range instructions {
		historyTypes[inst.Type] = true
	}

	// ENV from metadata (if not already in history)
	if len(meta.EnvVars) > 0 && !historyTypes[model.InstENV] {
		keys := make([]string, 0, len(meta.EnvVars))
		for k := range meta.EnvVars {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		b.WriteString("\n")
		for _, k := range keys {
			v := meta.EnvVars[k]
			if strings.ContainsAny(v, " \t\n\"") {
				b.WriteString(fmt.Sprintf("ENV %s=%q\n", k, v))
			} else {
				b.WriteString(fmt.Sprintf("ENV %s=%s\n", k, v))
			}
		}
	}

	// LABEL from metadata
	if len(meta.Labels) > 0 && !historyTypes[model.InstLABEL] {
		keys := make([]string, 0, len(meta.Labels))
		for k := range meta.Labels {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		b.WriteString("\n")
		for _, k := range keys {
			b.WriteString(fmt.Sprintf("LABEL %s=%q\n", k, meta.Labels[k]))
		}
	}

	// EXPOSE from metadata
	if len(meta.ExposedPorts) > 0 && !historyTypes[model.InstEXPOSE] {
		b.WriteString("\n")
		for _, port := range meta.ExposedPorts {
			b.WriteString(fmt.Sprintf("EXPOSE %s\n", port))
		}
	}

	// VOLUME from metadata
	if len(meta.Volumes) > 0 && !historyTypes[model.InstVOLUME] {
		b.WriteString("\n")
		for _, vol := range meta.Volumes {
			b.WriteString(fmt.Sprintf("VOLUME %q\n", vol))
		}
	}

	// WORKDIR from metadata (if not in history)
	if meta.WorkingDir != "" && !historyTypes[model.InstWORKDIR] {
		b.WriteString(fmt.Sprintf("\nWORKDIR %s\n", meta.WorkingDir))
	}

	// USER from metadata (if not in history)
	if meta.User != "" && !historyTypes[model.InstUSER] {
		b.WriteString(fmt.Sprintf("\nUSER %s\n", meta.User))
	}

	// History-derived instructions
	if len(instructions) > 0 {
		if mergeRuns {
			instructions = MergeRuns(instructions)
		}
		b.WriteString("\n")
		for _, inst := range instructions {
			rendered := renderInstruction(inst)
			if rendered != "" {
				b.WriteString(rendered)
				b.WriteString("\n")
			}
		}
	}

	// ENTRYPOINT from metadata (if not in history)
	if len(meta.Entrypoint) > 0 && !historyTypes[model.InstENTRYPOINT] {
		b.WriteString(fmt.Sprintf("\nENTRYPOINT %s\n", formatJSONCmd(meta.Entrypoint)))
	}

	// CMD from metadata (if not in history)
	if len(meta.Cmd) > 0 && !historyTypes[model.InstCMD] {
		b.WriteString(fmt.Sprintf("\nCMD %s\n", formatJSONCmd(meta.Cmd)))
	}

	return b.String()
}

// renderInstruction converts a single Instruction to its Dockerfile text.
func renderInstruction(inst model.Instruction) string {
	switch inst.Type {
	case model.InstRUN:
		return fmt.Sprintf("RUN %s", inst.Content)
	case model.InstCOPY:
		return fmt.Sprintf("COPY %s", inst.Content)
	case model.InstADD:
		return fmt.Sprintf("ADD %s", inst.Content)
	case model.InstWORKDIR:
		return fmt.Sprintf("WORKDIR %s", inst.Content)
	case model.InstENV:
		if len(inst.KVPairs) > 0 {
			var parts []string
			for k, v := range inst.KVPairs {
				if strings.ContainsAny(v, " \t\n\"") {
					parts = append(parts, fmt.Sprintf("%s=%q", k, v))
				} else {
					parts = append(parts, fmt.Sprintf("%s=%s", k, v))
				}
			}
			sort.Strings(parts)
			return fmt.Sprintf("ENV %s", strings.Join(parts, " "))
		}
		return ""
	case model.InstEXPOSE:
		return fmt.Sprintf("EXPOSE %s", inst.Content)
	case model.InstCMD:
		return formatCmdEntrypoint("CMD", inst)
	case model.InstENTRYPOINT:
		return formatCmdEntrypoint("ENTRYPOINT", inst)
	case model.InstLABEL:
		if len(inst.KVPairs) > 0 {
			var parts []string
			for k, v := range inst.KVPairs {
				parts = append(parts, fmt.Sprintf("%s=%q", k, v))
			}
			sort.Strings(parts)
			return fmt.Sprintf("LABEL %s", strings.Join(parts, " "))
		}
		return ""
	case model.InstUSER:
		return fmt.Sprintf("USER %s", inst.Content)
	case model.InstSTOPSIGNAL:
		return fmt.Sprintf("STOPSIGNAL %s", inst.Content)
	case model.InstARG:
		return fmt.Sprintf("ARG %s", inst.Content)
	case model.InstVOLUME:
		return formatCmdEntrypoint("VOLUME", inst)
	case model.InstSHELL:
		return formatCmdEntrypoint("SHELL", inst)
	case model.InstHEALTHCHECK:
		return fmt.Sprintf("HEALTHCHECK %s", inst.Content)
	case model.InstCOMMENT:
		return inst.Content
	default:
		return ""
	}
}

func formatCmdEntrypoint(keyword string, inst model.Instruction) string {
	if len(inst.Args) > 0 {
		return fmt.Sprintf("%s %s", keyword, formatJSONCmd(inst.Args))
	}
	if inst.Content != "" {
		return fmt.Sprintf("%s %s", keyword, inst.Content)
	}
	return ""
}

func formatJSONCmd(args []string) string {
	quoted := make([]string, len(args))
	for i, a := range args {
		quoted[i] = fmt.Sprintf("%q", a)
	}
	return fmt.Sprintf("[%s]", strings.Join(quoted, ", "))
}
